### PR TITLE
Master

### PR DESCRIPTION
**Pull request by narcolic**
Added icon and a package that merges all dlls to .exe file.

### CODE REVIEW

**Comment by Just2good** [comment]
Have to be very careful with icons because of LoL development policy which is why I haven't added one yet. Also I need to look at what those 2 Fody packages do first.

**Comment by narcolic** [comment]
I see, i wasn't aware of the icon policy. Are we ok to use icons for the items and champions though?

On the Fody packages give it some test with your release versions and auto updater. I couldnt test it with auto updater, but i believe it should work.

**Comment by narcolic** [comment]
Btw here is a link to Fody tool: [https://github.com/Fody/Costura](https://github.com/Fody/Costura)

**Comment by Just2good** [comment]
Champions, Classes, Origins, Items should be fine, its the brand of TFT/LoL that I'm pretty sure we cant use.

**Comment by Just2good** [comment]
Also looks good, if you can remove the icon, I'll just merge it in.

**Comment by narcolic** [comment]
sure thing, i ll close this and raise a new one.

**Pull request closed without merging**
