### PR TITLE
Polished autoupdater

### PR DESCRIPTION
**Pull request by novatorem**
Now has a a Yes/No dialogue option.
`Yes` downloads the zip to `cwd`, while `No` should never show the message box again.

Any idea why you got asked ∞ times to download the new update? Also, how does scope for partial classes work? Can I get the value of a string from `MainWindow` to `App`?

### CODE REVIEW

**Comment by Just2good** [comment]
Letting it get the current version from app.xaml.cs is completely fine. Going to see if this works properly.
Also https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/partial-classes-and-methods

**Comment by Just2good** [comment]
Works perfectly, changed the currentversion around to try different scenarios and no issues.

**Comment by novatorem** [comment]
Glad it worked! Can't figure out enough from your link, I'll keep trying to get currentVersion in only MainWindow so you don't have to change two variables every update. Also the user will never get prompted to AutoUpdate again, so might add it when right clicking to allow user to re-enable the check.

I'll put in more pull requests when it comes to it. Thanks for the overlay btw, it's been a blessing!

**Comment by Just2good** [comment]
Yeah it looks like it never asks again, and no way to enable it in property settings. Hmm

**Comment by Just2good** [comment]
Found where it stores the config

**Comment by novatorem** [comment]
Oh I kept it in there myself, so I set it up to it'd never ask again.
I'm working on letting you re-enable it and use a singleton class to call on version number, pull request soon :)

**Pull request merged**
