### PR TITLE
Update and rename ItemStrings_en-US.xaml to ItemStrings_pl.xaml

### PR DESCRIPTION
**Pull request by Jadowity336**
I uptaded all items and champions description in polish language version. I hope you will add it in next patch.

### CODE REVIEW

**Comment by Just2good** [comment]
You cant replace en-US, you have to make a new .xaml file. Also there is already an ItemStrings_PL.xaml so you'll have to go and edit that instead. Feel free to send another pull request with the correct method.

**Comment by Jadowity336** [comment]
> You cant replace en-US, you have to make a new .xaml file. Also there is already an ItemStrings_PL.xaml so you'll have to go and edit that instead. Feel free to send another pull request with the correct method.
Ive been never doing this before. As I see I can do a new file with name "ItemStrings_PL.xaml", but i cant change existing file, bacause it is not mine. If it is ok to just make new file ill send it. Unless I cannot do this that way, i need to know how to do this. Im waiting for responed.

**Comment by Just2good** [comment]
There is already a PL file which you can edit here https://github.com/Just2good/TFT-Overlay/blob/master/Resource/Localization/ItemStrings_PL.xaml

**Comment by Jadowity336** [comment]
I sent the newest version of my changes. I hope  everything is alright.

**Pull request closed without merging**
