### PR TITLE
Master

### PR DESCRIPTION
**Pull request by scrachatron**
Created a new base class for hopefully the development branch unfortunetly my knowledge of XAML is next to nothing could you advise on how to change all the images of champions from images to radial buttons like the home bar as im having trouble doing so

### CODE REVIEW

**Comment by scrachatron** [comment]
Abandoned after reading more of the patch notes but i would like to help if possible

**Comment by Just2good** [comment]
Okay so what I'm seeing is you turned the icon into a radio button and you want it to show something like a tooltip with the best of items. I don't mind adding this in now, especially since I added MVVM. Can just keep it on an entirely new resource page. It looks good btw, just need to fix up a few things and maybe just make the items appear in a new frame

**Comment by Just2good** [comment]
If you want I can merge, change it a bit to fit how it would look like, and then commit so you can follow it?

**Comment by scrachatron** [comment]
How id describe it would be you can "pin" units so when you're in carousal you can still remember what items you need or something like that (or eventually if you can get access to the legue api automatically do that (though might be cheating like that) 

You're more than welcome to add the new file in if you like if you think it's useful unfortunetly in the process i've messed my branch up wholeheartedly might just re-fork and hope that fixes it

**Comment by Just2good** [comment]
Yeah I saw the Revertception commits xD. Also the pin thing sound interesting but that might have to wait until the champions section is finished. Going to keep this open for later

**Comment by scrachatron** [comment]
no bother if you want i could do more of the champs follow the same kind of framework and add them to that class just might be something thats useful for new players to know what items are synergistic with which champs.

**Comment by Just2good** [comment]
Closing for now

**Pull request closed without merging**
